name: Lintic

on:
  pull_request:
    paths:
      - '**/*.rb'
  push:
    paths:
      - '**/*.rb'

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.head.repo.full_name == github.repository && !contains(github.event.pull_request.title, '[LINTIC]')

    steps:
      - uses: actions/checkout@v4

      - name: Fix linting errors with Lintic
        uses: shindi-renuo/lintic@main
        with:
          github-token: ${{ secrets.LINTIC_GITHUB_TOKEN }}
          ollama-model: ${{ secrets.LINTIC_OLLAMA_MODEL }}
          ollama-uri: ${{ secrets.LINTIC_OLLAMA_URI }}
          openai-api-key: ${{ secrets.LINTIC_OPENAI_API_KEY }}
